spring.application.name=sylva
spring.datasource.url=${SYLBA_URL}
spring.datasource.username=${SYLBA_USERNAME}
spring.datasource.password=${SYLBA_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

#spring.messages.basename=messages
#spring.messages.encoding=UTF-8
