spring.application.name=sylva
spring.datasource.url=${SYLBA_URL}
spring.datasource.username=${SYLBA_USERNAME}
spring.datasource.password=${SYLBA_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none

spring.messages.basename=messages
spring.messages.encoding=UTF-8


spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace